[project]
name = "adk-mcpgooglemaps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk[extensions,mcp]>=2.9.1",
    "google-genai>=2.23.0",
    "opentelemetry-api>=1.42.1",
    "opentelemetry-sdk>=1.42.1",
    "python-dotenv>=1.2.3",
]
